services:
  aistudio-shard-0:
    image: aistudio-websocket:async
    environment:
      - HG=true
      - NO_PROXY=localhost,127.0.0.1,::1,cliproxy-dr,moe-cli-proxy-dr,moe-cli-proxy-api,host.docker.internal,172.21.32.1
    networks:
      moe-infrastructure-network:
        aliases:
          - aistudio-shard
          - cliproxy-backend

  aistudio-shard-1:
    deploy:
      replicas: 0
